#! /usr/bin/env bash
# Copyright 2022 Yahoo Inc.
# Licensed under the terms of the Apache License 2.0. Please see LICENSE file in project root for terms.

set -euo pipefail

# We remove the cert folder to avoid "hostkey already exists" error:
rm -rf ssh-crt
mkdir -p ssh-crt

echo "Generating ssh ca key ..."
ssh-keygen -N "" -b 384 -t ecdsa -f "./ssh-crt/host_ca_key"

echo "Generating ssh host key ..."
ssh-keygen -N "" -b 384 -t ecdsa -f "./ssh-crt/hostkey"

echo "Signing generated keys..."
ssh-keygen -s "./ssh-crt/host_ca_key" -I "generated by sample script" -h -n "localhost" -V "+52w" "ssh-crt/hostkey.pub"
