// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/theparanoids/ysshra/agent/shimagent (interfaces: ShimAgent)

// Package yubiagent is a generated GoMock package.
package yubiagent

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	ssh "golang.org/x/crypto/ssh"
	agent "golang.org/x/crypto/ssh/agent"
)

// MockShimAgent is a mock of ShimAgent interface.
type MockShimAgent struct {
	ctrl     *gomock.Controller
	recorder *MockShimAgentMockRecorder
}

// MockShimAgentMockRecorder is the mock recorder for MockShimAgent.
type MockShimAgentMockRecorder struct {
	mock *MockShimAgent
}

// NewMockShimAgent creates a new mock instance.
func NewMockShimAgent(ctrl *gomock.Controller) *MockShimAgent {
	mock := &MockShimAgent{ctrl: ctrl}
	mock.recorder = &MockShimAgentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShimAgent) EXPECT() *MockShimAgentMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockShimAgent) Add(arg0 agent.AddedKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockShimAgentMockRecorder) Add(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockShimAgent)(nil).Add), arg0)
}

// AddHardCert mocks base method.
func (m *MockShimAgent) AddHardCert(arg0 ssh.PublicKey, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddHardCert", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddHardCert indicates an expected call of AddHardCert.
func (mr *MockShimAgentMockRecorder) AddHardCert(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHardCert", reflect.TypeOf((*MockShimAgent)(nil).AddHardCert), arg0, arg1)
}

// Close mocks base method.
func (m *MockShimAgent) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockShimAgentMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockShimAgent)(nil).Close))
}

// Forward mocks base method.
func (m *MockShimAgent) Forward(arg0 []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Forward", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Forward indicates an expected call of Forward.
func (mr *MockShimAgentMockRecorder) Forward(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Forward", reflect.TypeOf((*MockShimAgent)(nil).Forward), arg0)
}

// List mocks base method.
func (m *MockShimAgent) List() ([]*agent.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]*agent.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockShimAgentMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockShimAgent)(nil).List))
}

// Lock mocks base method.
func (m *MockShimAgent) Lock(arg0 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lock", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Lock indicates an expected call of Lock.
func (mr *MockShimAgentMockRecorder) Lock(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lock", reflect.TypeOf((*MockShimAgent)(nil).Lock), arg0)
}

// Remove mocks base method.
func (m *MockShimAgent) Remove(arg0 ssh.PublicKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockShimAgentMockRecorder) Remove(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockShimAgent)(nil).Remove), arg0)
}

// RemoveAll mocks base method.
func (m *MockShimAgent) RemoveAll() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAll")
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAll indicates an expected call of RemoveAll.
func (mr *MockShimAgentMockRecorder) RemoveAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAll", reflect.TypeOf((*MockShimAgent)(nil).RemoveAll))
}

// Sign mocks base method.
func (m *MockShimAgent) Sign(arg0 ssh.PublicKey, arg1 []byte) (*ssh.Signature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sign", arg0, arg1)
	ret0, _ := ret[0].(*ssh.Signature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sign indicates an expected call of Sign.
func (mr *MockShimAgentMockRecorder) Sign(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sign", reflect.TypeOf((*MockShimAgent)(nil).Sign), arg0, arg1)
}

// Signers mocks base method.
func (m *MockShimAgent) Signers() ([]ssh.Signer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signers")
	ret0, _ := ret[0].([]ssh.Signer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signers indicates an expected call of Signers.
func (mr *MockShimAgentMockRecorder) Signers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signers", reflect.TypeOf((*MockShimAgent)(nil).Signers))
}

// Unlock mocks base method.
func (m *MockShimAgent) Unlock(arg0 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unlock", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unlock indicates an expected call of Unlock.
func (mr *MockShimAgentMockRecorder) Unlock(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlock", reflect.TypeOf((*MockShimAgent)(nil).Unlock), arg0)
}

// Wait mocks base method.
func (m *MockShimAgent) Wait(arg0 byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Wait indicates an expected call of Wait.
func (mr *MockShimAgentMockRecorder) Wait(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockShimAgent)(nil).Wait), arg0)
}
